# Generated by Django 4.1.4 on 2022-12-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='minute',
            new_name='minutes',
        ),
    ]
